from steps import ask_llm


def generate_final_response(db_data: dict, user_intent: str, user_query: str) -> str:
    """
    Combines DB data, LLM-generated info, and Places data to produce the final structured output.
    Calls ask_llm() and returns the LLM response.
    """

    prompt = f"""
You are the Final Response Generator for a travel assistant.

### USER QUERY
"{user_query}"

### USER INTENT (interpreted meaning)
{user_intent}

### DATA SOURCES
You have 3 types of data generated by upstream systems:

1. **User Profile Data (db_user)**  
   This contains personal user preferences or profile information.  
   Example → languages spoken, budget, preferences.  
   DATA:
   {db_data.get("db_user")}

2. **Places Data (db_places)**  
   These are results from Google Places API relevant to the query.  
   DATA:
   {db_data.get("db_places")}

3. **LLM Reasoning Data (db_llm)**  
   These are knowledge-based or reasoning-based results from your secondary LLM stage.  
   DATA:
   {db_data.get("db_llm")}

### TASK
Using ALL the above information, produce the **final output** for the user’s query.
This output must be:
- Correct
- Fully detailed
- Easy to read
- Well-structured
- Helpful and naturally written
- NO placeholders anywhere
- Use all useful information from db_user, db_places, and db_llm
- If db data is empty for a section, ignore that section gracefully.

### OUTPUT FORMAT
Return the final answer in the following structure:

---
**Final Answer Summary**
A short, clear summary of the result.

**User-Relevant Insights**
List of important insights extracted from db_user and db_llm.

**Recommended Places / Results**
Structured list or bullets using db_places data.

**Reasoning Notes**
Explain briefly (in 2–3 lines) how the result was formed.
---

Do NOT output JSON.  
Do NOT output metadata.  
Just produce the final formatted natural-language answer.
"""

    return ask_llm(prompt)
